# Generated by Django 5.1.2 on 2025-03-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
